--- 02 block ---

select *
from employees
where salary between 3000 and 10000;

select *
from employees
where department_id in (10, 20, 50);

select *
from employees
where commission_pct is null;

select *
from employees
where last_name like 'A%';

select *
from EMPLOYEES
WHERE JOB_ID LIKE '%\_%' ESCAPE '\';

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID NOT IN (10, 50)
  AND SALARY > 6000;

SELECT *
FROM EMPLOYEES
ORDER BY COMMISSION_PCT NULLS LAST;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
ORDER BY 4 DESC;

SELECT EMPLOYEE_ID, UPPER(FIRST_NAME)
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) > 7;

SELECT ADD_MONTHS(SYSDATE, 6)
FROM DUAL;

SELECT EMPLOYEE_ID, FIRST_NAME, ROUND(SALARY, -3), TRUNC(SALARY, -3)
FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES
WHERE MOD(EMPLOYEE_ID, 2) = 0;
SELECT MOD(SALARY, 1000)
FROM EMPLOYEES
WHERE MOD(EMPLOYEE_ID, 2) = 0;

SELECT ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE), 0)
FROM EMPLOYEES;

SELECT HIRE_DATE, ADD_MONTHS(HIRE_DATE, 12)
FROM EMPLOYEES;

UPDATE EMPLOYEES
SET HIRE_DATE = HIRE_DATE - 365
WHERE 4 = 4;

COMMIT;
SELECT *
FROM EMPLOYEES;

SELECT NEXT_DAY(HIRE_DATE, 'FRIDAY') AS RESULT
FROM EMPLOYEES;

SELECT LAST_DAY(HIRE_DATE) AS RESULT
FROM EMPLOYEES;

SELECT ROUND(HIRE_DATE, 'DAY')
FROM EMPLOYEES;

SELECT TO_DATE(ROUND(HIRE_DATE, 'DAY'), 'DD-MON-RR')
FROM EMPLOYEES;

SELECT INITCAP(EMAIL)
FROM EMPLOYEES;

SELECT TRIM('#' FROM '##ADAM###')
FROM DUAL;

SELECT TRIM(BOTH '@' FROM '@ADAM@@')
FROM DUAL;

SELECT SUBSTR(FIRST_NAME, 1, 3)
FROM EMPLOYEES;
SELECT SUBSTR(FIRST_NAME, -3, 2)
FROM EMPLOYEES;

SELECT RPAD(LPAD(SALARY, 11, '#'), 15, '^')
FROM EMPLOYEES;

SELECT INSTR(LOWER(FIRST_NAME), 'a')
from employees;

SELECT REPLACE(lower(FIRST_NAME), 'a')
from employees;

select sysdate + 7 + 1 / 24
from dual;


-- re 8/29/2026

select *
from employees
where salary between 3000 and 5000;

select *
from employees
where DEPARTMENT_ID IN (10, 20, 50);

SELECT *
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL;

SELECT *
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'A%';

SELECT *
FROM EMPLOYEES
WHERE JOB_ID LIKE '%/_%' ESCAPE '/';

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID NOT IN (10, 50)
  AND SALARY > 6000;

SELECT *
FROM EMPLOYEES
ORDER BY COMMISSION_PCT NULLS LAST;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
ORDER BY 4 DESC;

SELECT UPPER(LAST_NAME)
FROM EMPLOYEES
WHERE LENGTH(LAST_NAME) > 7;

SELECT ADD_MONTHS(SYSDATE, 6)
FROM DUAL;

SELECT ROUND(SALARY, -3), TRUNC(SALARY, -3)
FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES
WHERE MOD(EMPLOYEE_ID, 2) = 0;

SELECT SALARY, MOD(SALARY, 1000)
FROM EMPLOYEES;

SELECT HIRE_DATE, ROUND(MONTHS_BETWEEN(HIRE_DATE, SYSDATE), 0)
FROM EMPLOYEES;

SELECT ADD_MONTHS(HIRE_DATE, 12)
FROM EMPLOYEES;

SELECT NEXT_DAY(HIRE_DATE, 'FRIDAY')
FROM EMPLOYEES;

SELECT LAST_DAY(HIRE_DATE)
FROM EMPLOYEES;

SELECT ROUND(HIRE_DATE), TRUNC(HIRE_DATE)
FROM EMPLOYEES;

SELECT INITCAP(EMAIL)
FROM EMPLOYEES;

SELECT TRIM(BOTH '#' FROM '##ADAM###')
FROM DUAL;

SELECT SUBSTR(FIRST_NAME, 1, 3)
FROM EMPLOYEES;

SELECT SUBSTR(FIRST_NAME, -3, 3)
FROM EMPLOYEES;

SELECT RPAD(LPAD(SALARY, 10, '$'), 15, '@')
FROM EMPLOYEES;

SELECT FIRST_NAME, INSTR(LOWER(FIRST_NAME), 'a')
FROM EMPLOYEES;

SELECT REPLACE(lower(FIRST_NAME), 'a', '@') AS RESULT
FROM EMPLOYEES;

SELECT SYSDATE + 7 + 1 / 24 AS RESULT
FROM DUAL;

SELECT TO_CHAR(SALARY, '99,999.99')
FROM EMPLOYEES;

SELECT TO_CHAR(HIRE_DATE, 'YYYY-MM-DD (FMDAY)')
FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE > TO_DATE('15-02-2022', 'DD-MM-YYYY');

SELECT TO_NUMBER('12,500.75', '99,999.00')
FROM DUAL;

SELECT TRIM(BOTH ' ' FROM EMAIL)
FROM EMPLOYEES;

SELECT NVL(COMMISSION_PCT, 0)
FROM EMPLOYEES;

SELECT NVL2(COMMISSION_PCT, 'YES', 'NO')
FROM EMPLOYEES;

SELECT NULLIF(SALARY, 9000)
FROM EMPLOYEES;

SELECT COALESCE(COMMISSION_PCT, SALARY, 0)
FROM EMPLOYEES;

SELECT DECODE(SALARY, 9000, SALARY + 100000)
FROM EMPLOYEES;

SELECT CASE DEPARTMENT_ID
           WHEN 10 THEN 'IT'
           WHEN 20 THEN 'HR'
           ELSE 'OTHER'
           END
           AS DEP
FROM EMPLOYEES;

SELECT CASE
           WHEN SALARY < 5000 THEN 'LOW'
           WHEN SALARY < 8000 THEN 'MEDIUM'
           ELSE 'HIGH'
           END
           AS SALARY
FROM EMPLOYEES;

SELECT NVL(TO_CHAR(SALARY, 'FM99,999.00'), 'NO SALARY') AS RESULT
FROM EMPLOYEES;

SELECT CASE
           WHEN HIRE_DATE < TO_DATE('11-09-2024', 'DD-MM-YYYY') THEN 'OLD'
           ELSE 'NEW'
           END
           AS AGE
FROM EMPLOYEES;

SELECT COALESCE(COMMISSION_PCT, SALARY, 0) AS MONEY
FROM EMPLOYEES;

SELECT CASE
           WHEN LENGTH(FIRST_NAME) > 5 THEN UPPER(FIRST_NAME)
           ELSE FIRST_NAME
           END
           AS NAME
FROM EMPLOYEES;

SELECT NVL(NULLIF (SALARY, 0),999) FROM EMPLOYEES;

SELECT COUNT(*) FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL;

SELECT CASE
    WHEN COMMISSION_PCT IS NOT NULL THEN 'BONUS'
    ELSE 'NONE'
    END
    AS COMMISSION
FROM EMPLOYEES;

SELECT NULLIF (SALARY, 9000) FROM EMPLOYEES;

SELECT DECODE (salary, 9000, 'true', 'false') from EMPLOYEES;