-- ORACLE DB 6 PART --

SELECT FIRST_NAME AS NAME, SALARY AS RESULT
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG (SALARY) FROM EMPLOYEES);

SELECT DEPARTMENT_ID AS DEP, ROUND (AVG (SALARY)) AS AVG
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
                     HAVING AVG (SALARY) > (SELECT AVG (SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = 50);

SELECT FIRST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME LIKE 'S%');

SELECT FIRST_NAME FROM EMPLOYEES WHERE SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 30);

SELECT FIRST_NAME FROM EMPLOYEES WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 30);

SELECT FIRST_NAME FROM EMPLOYEES E WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = E.DEPARTMENT_ID);

SELECT D.DEPARTMENT_ID AS DEP
FROM DEPARTMENTS D
WHERE (SELECT COUNT (*) FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID) > 3;

