-------10-1-26-------

CREATE TABLE STUDENTZ (
ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2 (128) DEFAULT NULL PRIMARY KEY,
    LAST_NAME VARCHAR2 (128),
    AGE NUMBER CHECK (LENGTH(AGE) > 0),
    BIRTH_DATE DATE DEFAULT SYSDATE
);

UPDATE STUDENTZ SET AGE = 4 WHERE 4=4;
DELETE STUDENTZ WHERE 'EMAIL' IS NULL;



ALTER TABLE STUDENTZ ADD (EMAIL VARCHAR2 (100));

CREATE TABLE GRADEZ (
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2 (22) CHECK (LENGTH (NAME) BETWEEN 5 AND 10),
  ST_ID VARCHAR2 (22),
    FOREIGN KEY (ST_ID) REFERENCES STUDENTZ(ID)
);

SELECT NVL(FIRST_NAME, 'NONE') FROM STUDENTZ WHERE FIRST_NAME IS NULL;

INSERT INTO STUDENTZ (ID, FIRST_NAME, LAST_NAME, AGE, BIRTH_DATE) VALUES
(5, UPPER('baba'), NULL, NULL, TO_DATE('25-DEC-2024','DD-MON-YYYY'));

UPDATE STUDENTZ SET FIRST_NAME = INITCAP(FIRST_NAME) WHERE FIRST_NAME IS NULL;





INSERT INTO STUDENTZ (ID, FIRST_NAME, LAST_NAME, AGE, BIRTH_DATE)
VALUES (1, 'JOHN', 'CENA', NULL, TO_DATE('15-03-2024', 'DD-MM-YYYY'));

INSERT INTO STUDENTZ (ID, FIRST_NAME, LAST_NAME, AGE, BIRTH_DATE)
VALUES (3, 'JOHN', 'CENA', NULL, SYSDATE);

INSERT INTO STUDENTZ (ID, FIRST_NAME, LAST_NAME, AGE, BIRTH_DATE)
VALUES (4, UPPER('admin'), NULL, NULL, SYSDATE);

UPDATE STUDENTZ SET AGE = 1 WHERE AGE IS NULL;
UPDATE STUDENTZ SET AGE = NVL(AGE, 1) WHERE AGE IS NULL;
UPDATE STUDENTZ SET AGE = COALESCE (AGE, 1) WHERE AGE IS NULL;

