-- re 04-09-2026

SELECT *
FROM EMPLOYEES;

SELECT COUNT(COMMISSION_PCT)
FROM EMPLOYEES;

SELECT COUNT(*)
FROM EMPLOYEES;

SELECT SUM(SALARY)
FROM EMPLOYEES;

SELECT ROUND(AVG(SALARY), 2)
FROM EMPLOYEES;

SELECT MIN(HIRE_DATE) MIN, MAX(HIRE_DATE) AS MAX
FROM EMPLOYEES;

SELECT DEPARTMENT_ID AS DEP,
       ROUND(AVG(SALARY), 2)
                     AS SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID      AS DEP,
       COUNT(EMPLOYEE_ID) AS COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID AS DEP, JOB_ID AS JOB, ROUND(AVG(SALARY), 2) AS AVG
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID;

SELECT DEPARTMENT_ID AS DEP, AVG(SALARY) AS SAL
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > 7000;

SELECT DEPARTMENT_ID AS DEP, COUNT(EMPLOYEE_ID)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(EMPLOYEE_ID) > 5;

SELECT DEPARTMENT_ID, MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY > 3000
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY) > 10000;

SELECT COUNT(DISTINCT DEPARTMENT_ID) AS COUNTER
FROM EMPLOYEES;

SELECT CASE
           WHEN SALARY < 4000 THEN 'LOW'
           WHEN SALARY BETWEEN 4001 AND 7999 THEN 'MEDIUM'
           ELSE 'HIGH'
           END
           AS SALARY,
       COUNT(*)
FROM EMPLOYEES
GROUP BY CASE
             WHEN SALARY < 4000 THEN 'LOW'
             WHEN SALARY BETWEEN 4001 AND 7999 THEN 'MEDIUM'
             ELSE 'HIGH'
             END;

SELECT CASE
           WHEN COMMISSION_PCT IS NULL THEN 'NO'
           ELSE 'HAS'
           END
           AS COMMISSION,
       COUNT(*)
FROM EMPLOYEES
GROUP BY CASE
             WHEN COMMISSION_PCT IS NULL THEN 'NO'
             ELSE 'HAS'
             END;

SELECT SUM(CASE WHEN COMMISSION_PCT IS NOT NULL THEN 1 END) AS NONE,
       SUM(CASE WHEN COMMISSION_PCT IS NULL THEN 1 END)     AS HAS
FROM EMPLOYEES;

SELECT CASE
           WHEN DEPARTMENT_ID = 50 THEN '50'
           ELSE 'OTHER'
           END
           AS DEP,
       COUNT(*)
FROM EMPLOYEES
GROUP BY CASE
             WHEN DEPARTMENT_ID = 50 THEN '50'
             ELSE 'OTHER'
             END;

SELECT NVL2(MANAGER_ID, TO_CHAR(MANAGER_ID), 'NO MANAGER'), COUNT(*)
FROM EMPLOYEES
GROUP BY NVL2(MANAGER_ID, TO_CHAR(MANAGER_ID), 'NO MANAGER');

SELECT DEPARTMENT_ID, COUNT(COMMISSION_PCT)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT CASE
           WHEN COMMISSION_PCT IS NULL THEN 'HAS'
           ELSE 'NONE'
           END
           AS COMMISSION,
       ROUND(AVG(SALARY), 2)
FROM EMPLOYEES
GROUP BY CASE
             WHEN COMMISSION_PCT IS NULL THEN 'HAS'
             ELSE 'NONE'
             END;

SELECT CASE
           WHEN MANAGER_ID IS NULL THEN 'NO'
           ELSE 'HAS'
           END,
       ROUND(AVG(SALARY))
FROM EMPLOYEES
GROUP BY CASE
             WHEN MANAGER_ID IS NULL THEN 'NO'
             ELSE 'HAS'
             END
HAVING AVG(SALARY) > 6000;

-- re 05-09-2026

SELECT COUNT(*)
FROM EMPLOYEES;

SELECT COUNT(COMMISSION_PCT)
FROM EMPLOYEES;

SELECT SUM(SALARY)
FROM EMPLOYEES;

SELECT ROUND(AVG(SALARY), 2)
FROM EMPLOYEES;

SELECT MAX(HIRE_DATE), MIN(HIRE_DATE)
FROM EMPLOYEES;

SELECT DEPARTMENT_ID, ROUND(AVG(SALARY))
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, JOB_ID, ROUND(AVG(SALARY))
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID;

SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > 7000;

SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 5;

SELECT COUNT(DISTINCT DEPARTMENT_ID) AS DEP
FROM EMPLOYEES;

SELECT CASE
           WHEN SALARY < 3999 THEN 'LOW'
           WHEN SALARY BETWEEN 4000 AND 7999 THEN 'MEDIUM'
           ELSE 'HIGH'
           END
           AS SALARY,
       COUNT(*)
FROM EMPLOYEES
GROUP BY CASE
             WHEN SALARY < 3999 THEN 'LOW'
             WHEN SALARY BETWEEN 4000 AND 7999 THEN 'MEDIUM'
             ELSE 'HIGH'
             END;

SELECT CASE
           WHEN COMMISSION_PCT IS NOT NULL THEN 'HAS'
           ELSE 'NONE'
           END
           AS COMMISSION,
       COUNT(*)
FROM EMPLOYEES
GROUP BY CASE
             WHEN COMMISSION_PCT IS NOT NULL THEN 'HAS'
             ELSE 'NONE'
             END;


SELECT SUM (CASE WHEN COMMISSION_PCT IS NULL THEN 1 END) AS HAS,
    SUM (CASE WHEN COMMISSION_PCT IS NOT NULL THEN 1 END) AS NONE
FROM EMPLOYEES;

SELECT CASE
    WHEN DEPARTMENT_ID = 50 THEN '50'
    ELSE 'OTHER'
    END AS DEP,
    SUM (SALARY) AS SALARY
FROM EMPLOYEES
GROUP BY
    CASE
        WHEN DEPARTMENT_ID = 50 THEN '50'
        ELSE 'OTHER'
        END;

SELECT NVL (TO_CHAR(MANAGER_ID), 'NO MANAGER') AS ID,
       COUNT (*)
FROM EMPLOYEES
GROUP BY NVL (TO_CHAR(MANAGER_ID), 'NO MANAGER');


