--INNER JOIN-- ЛИШЕ ТІ РЯДКИ ЩО МАЮТЬ ЗБІГ В ОБОХ TABLES
SELECT E.EMAIL, D.DEPARTMENT_NAME
FROM EMPLOYEES E
         INNER JOIN DEPARTMENTS D
                    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- JOIN USING -- ПРИХОВУЄТЬСЯ ДУБЛЬ КОЛОНКИ
SELECT EMAIL, DEPARTMENT_NAME
FROM EMPLOYEES E
         INNER JOIN DEPARTMENTS D
                    USING (DEPARTMENT_ID);

-- NATURAL JOIN -- АВТОМАТИЧНЕ ЗЄДНАННЯ, НЕБЕЗПЕЧНО
SELECT EMAIL, DEPARTMENT_NAME
FROM EMPLOYEES E
         NATURAL JOIN DEPARTMENTS D;

-- JOIN + WHERE
SELECT E.EMAIL, D.DEPARTMENT_NAME
FROM EMPLOYEES E
         JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
WHERE E.DEPARTMENT_ID = 50;

-- SELF JOIN
SELECT E.LAST_NAME, D.LAST_NAME
FROM EMPLOYEES E
         JOIN EMPLOYEES D ON E.MANAGER_ID = D.EMPLOYEE_ID;

-- LEFT OUTER JOIN
SELECT E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
         LEFT JOIN DEPARTMENTS D
                   ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- RIGHT OUTER JOIN
SELECT E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
         RIGHT JOIN DEPARTMENTS D
                    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- FULL OUTER JOIN
SELECT E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
         FULL JOIN DEPARTMENTS D
                   ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- FULL OUTER JOIN
SELECT E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
         CROSS JOIN DEPARTMENTS D;

-- re join

SELECT E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
         JOIN DEPARTMENTS D
              ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
         JOIN DEPARTMENTS D
              USING (DEPARTMENT_ID);

SELECT E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
         NATURAL JOIN DEPARTMENTS D;

SELECT E.FIRST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
         JOIN DEPARTMENTS D
              ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
WHERE D.DEPARTMENT_ID = 50;

SELECT E.FIRST_NAME AS EMPLOYEE, D.FIRST_NAME AS MANAGER
FROM EMPLOYEES E
         JOIN EMPLOYEES D
              ON (E.EMPLOYEE_ID = D.MANAGER_ID);

SELECT D.DEPARTMENT_NAME,
       COUNT(E.EMPLOYEE_ID)
FROM EMPLOYEES E
         LEFT JOIN DEPARTMENTS D
                   ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME;



