SELECT * FROM EMPLOYEES;

SELECT TO_CHAR(SALARY, 'FM99,999.00') || ' $'  FROM EMPLOYEES;

SELECT TO_CHAR(HIRE_DATE, 'DD-MON-RR (FMDAY)') FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE HIRE_DATE > TO_DATE('15-02-2026', 'DD-MM-YYYY');

SELECT TO_NUMBER ('12,500.75', '99,999.00')AS RESULT FROM DUAL;

SELECT TRIM (' ' FROM UPPER(FIRST_NAME)) FROM EMPLOYEES;

SELECT NVL(COMMISSION_PCT, 0) AS COMMISSION FROM EMPLOYEES;

SELECT NVL2(COMMISSION_PCT, 'YES', 'NO') FROM EMPLOYEES;

SELECT NULLIF (SALARY, 9000) FROM EMPLOYEES;

SELECT COALESCE (SALARY, COMMISSION_PCT, 0)AS VALUE FROM EMPLOYEES;

SELECT DECODE (SALARY, 9000, NULL, SALARY + 100000) FROM EMPLOYEES;

SELECT
CASE DEPARTMENT_ID
WHEN 10 THEN 'IT'
WHEN 20 THEN 'HR'
ELSE 'NONE'
END
AS RESULT
FROM EMPLOYEES;

SELECT CASE
WHEN SALARY < 4000 THEN 'LOW'
WHEN SALARY < 8000 THEN 'MEDIAS'
ELSE 'HIGH'
END
AS RESULT
FROM EMPLOYEES;

SELECT NVL (TO_CHAR(COMMISSION_PCT, 'FM99,999.00'), 'NONE' ) FROM EMPLOYEES;

SELECT CASE
    WHEN HIRE_DATE < TO_DATE('01-01-2023', 'DD-MM-YYYY') THEN 'OLD'
ELSE 'NEW'
END
AS RESULT
FROM EMPLOYEES;

SELECT EMPLOYEE_ID AS ID, COALESCE  (COMMISSION_PCT, SALARY, 0)
    AS RESULT FROM EMPLOYEES;

SELECT CASE
    WHEN LENGTH (FIRST_NAME) > 5 THEN UPPER(FIRST_NAME)
ELSE FIRST_NAME
END
AS NAMES
FROM EMPLOYEES;

SELECT NVL (NULLIF (SALARY, 9000), 999) FROM EMPLOYEES;

SELECT DECODE (DEPARTMENT_ID, 10, 'IT', 20, 'HR', 'ELSE') FROM EMPLOYEES;

SELECT COUNT(*) FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL;

SELECT NVL2 (COMMISSION_PCT, 'BONUS', 'NONE') FROM EMPLOYEES;

