--- 02 block ---

select * from employees where salary between 3000 and 10000;

select * from employees where department_id in (10, 20, 50);

select * from employees where commission_pct is null;

select * from employees where last_name like 'A%';

select * from EMPLOYEES WHERE JOB_ID LIKE '%\_%' ESCAPE '\';

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID NOT IN (10, 50) AND SALARY > 6000;

SELECT * FROM EMPLOYEES ORDER BY COMMISSION_PCT NULLS LAST;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
ORDER BY 4 DESC;

SELECT EMPLOYEE_ID, UPPER(FIRST_NAME) FROM EMPLOYEES WHERE LENGTH(FIRST_NAME) > 7;

SELECT ADD_MONTHS (SYSDATE, 6) FROM DUAL;

SELECT EMPLOYEE_ID, FIRST_NAME, ROUND (SALARY, -3), TRUNC (SALARY, -3) FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE MOD(EMPLOYEE_ID, 2) = 0;
SELECT MOD(SALARY, 1000) FROM EMPLOYEES WHERE MOD(EMPLOYEE_ID, 2) = 0;

SELECT ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE), 0) FROM EMPLOYEES;

SELECT HIRE_DATE, ADD_MONTHS(HIRE_DATE, 12) FROM EMPLOYEES;

UPDATE EMPLOYEES SET HIRE_DATE = HIRE_DATE-365 WHERE 4=4;

COMMIT;
SELECT * FROM EMPLOYEES;

SELECT NEXT_DAY(HIRE_DATE, 'FRIDAY') AS RESULT FROM EMPLOYEES;

SELECT LAST_DAY(HIRE_DATE) AS RESULT FROM EMPLOYEES;

SELECT ROUND (HIRE_DATE, 'DAY') FROM EMPLOYEES;

SELECT TO_DATE(ROUND (HIRE_DATE, 'DAY'), 'DD-MON-RR' ) FROM EMPLOYEES;

SELECT INITCAP (EMAIL) FROM EMPLOYEES;

SELECT TRIM('#' FROM '##ADAM###') FROM DUAL;

SELECT TRIM (BOTH '@' FROM '@ADAM@@') FROM DUAL;

SELECT SUBSTR (FIRST_NAME, 1, 3) FROM EMPLOYEES;
SELECT SUBSTR (FIRST_NAME, -3, 2) FROM EMPLOYEES;

SELECT RPAD(LPAD(SALARY, 11, '#'), 15, '^') FROM EMPLOYEES;

SELECT INSTR(LOWER(FIRST_NAME), 'a') from employees;

SELECT REPLACE (lower(FIRST_NAME), 'a') from employees;

select sysdate+7+1/24 from dual;