-------10-1-26-------

CREATE TABLE STUDENTZ (
ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2 (128),
    LAST_NAME VARCHAR2 (128),
    AGE NUMBER CHECK (LENGTH(AGE) > 0),
    BIRTH_DATE DATE not null
);

INSERT INTO STUDENTZ (ID, FIRST_NAME, LAST_NAME, AGE, BIRTH_DATE)
VALUES (1, 'JOHN', 'CENA', NULL, TO_DATE('15-03-2024', 'DD-MM-YYYY'));

INSERT INTO STUDENTZ (ID, FIRST_NAME, LAST_NAME, AGE, BIRTH_DATE)
VALUES (3, 'JOHN', 'CENA', NULL, SYSDATE);

INSERT INTO STUDENTZ (ID, FIRST_NAME, LAST_NAME, AGE, BIRTH_DATE)
VALUES (4, UPPER('admin'), NULL, NULL, SYSDATE);

UPDATE STUDENTZ SET AGE = 1 WHERE AGE IS NULL;
UPDATE STUDENTZ SET AGE = NVL(AGE, 1) WHERE AGE IS NULL;


